# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_and_telemetry/grpc_python/dummy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control_and_telemetry/grpc_python/dummy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-control_and_telemetry/grpc_python/dummy.proto\"\x07\n\x05\x45mpty\"\x19\n\x05\x44ummy\x12\x10\n\x08response\x18\x01 \x01(\t2-\n\x0c\x44ummyService\x12\x1d\n\x0bGetResponse\x12\x06.Empty\x1a\x06.Dummyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_and_telemetry.grpc_python.dummy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=49
  _globals['_EMPTY']._serialized_end=56
  _globals['_DUMMY']._serialized_start=58
  _globals['_DUMMY']._serialized_end=83
  _globals['_DUMMYSERVICE']._serialized_start=85
  _globals['_DUMMYSERVICE']._serialized_end=130
# @@protoc_insertion_point(module_scope)
