# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_management.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x65vice_management.proto\x12\nhelloworld\"\x1a\n\nDeviceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x0e\x44\x65viceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\rDeviceManager\x12\x44\n\x0eRegisterDevice\x12\x16.helloworld.DeviceInfo\x1a\x1a.helloworld.DeviceResponseB\x06\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\003HLW'
  _globals['_DEVICEINFO']._serialized_start=39
  _globals['_DEVICEINFO']._serialized_end=65
  _globals['_DEVICERESPONSE']._serialized_start=67
  _globals['_DEVICERESPONSE']._serialized_end=117
  _globals['_DEVICEMANAGER']._serialized_start=119
  _globals['_DEVICEMANAGER']._serialized_end=204
# @@protoc_insertion_point(module_scope)
